# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0003_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
