# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0004_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='Burasi doldurulmalidir', max_length=120),
        ),
    ]
