# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0005_myuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
