# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0006_delete_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.AddField(
            model_name='contact',
            name='upload',
            field=models.FileField(default=0, upload_to='profile/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
