# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0008_auto_20160721_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='upload',
        ),
    ]
