# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0011_auto_20160726_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='isim',
        ),
    ]
