# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0012_auto_20160725_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sifre',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sifre_onay',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 7, 25, 8, 15, 48, 814000, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
