# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0014_auto_20160725_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='bolum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gorev',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='kurum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='posta_kodu',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='uzmanlik',
        ),
    ]
