# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0013_post'),
        ('bildirge', '0015_auto_20160725_1213'),
        ('bildirge', '0009_auto_20160727_1532'),
    ]

    operations = [
    ]
