# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0016_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='Burasi doldurulmalidir', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='isim',
            field=models.CharField(default='Burasi doldurulmalidir', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='soyad',
            field=models.CharField(default='Burasi doldurulmalidir', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bildirge.Doc'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
