# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0017_auto_20160727_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='isim',
            new_name='username',
        ),
    ]
