# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0018_auto_20160727_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sifre',
            field=models.CharField(default='Burasi doldurulmalidir', max_length=120),
        ),
    ]
