# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0019_contact_sifre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='isim',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sifre',
        ),
        migrations.AlterField(
            model_name='contact',
            name='unvan',
            field=models.CharField(choices=[(None, 'Lutfen seciniz'), ('P', 'Prof. Dr.'), ('D', 'Doc. Dr.'), ('Y', 'Yard. Doc. Dr.'), ('U', 'Uzm. Dr.'), ('Dr', 'Dr.'), ('B', 'Biyolog'), ('O', 'Ogr. Gor.'), ('A', 'Aras. Gor.'), ('T', 'Teknisyen'), ('M', 'Muhendis'), ('D.O.', 'Doktora Ogrencisi'), ('Mr', 'Bay'), ('Ms', 'Bayan')], default=None, max_length=15),
        ),
    ]
