# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bildirge', '0020_auto_20160728_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
