# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0022_remove_contact_cinsiyet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_info',
        ),
        migrations.AddField(
            model_name='doc',
            name='event',
            field=models.CharField(choices=[(None, 'Lutfen seciniz'), ('GTZ', 'Genc Turkiye Zirvesi'), ('TR', 'Transist')], default=None, max_length=15),
        ),
    ]
