# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0023_auto_20160728_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='event',
            field=models.CharField(choices=[(None, 'Lutfen seciniz'), ('GTZ', 'Genc Turkiye Zirvesi'), ('TR', 'Transist')], default=None, max_length=15, null=True),
        ),
    ]
