# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0025_auto_20160728_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='event',
        ),
    ]
