# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0031_auto_20160728_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
