# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0034_auto_20160728_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
