# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0035_auto_20160728_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='event',
            field=models.CharField(blank=True, choices=[(None, 'Lutfen seciniz'), ('gtz', 'Genclik zirvesi'), ('tr', 'transist')], max_length=15, null=True),
        ),
    ]
