# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0036_auto_20160728_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='event',
            field=models.CharField(choices=[(None, 'Lutfen seciniz'), ('gtz', 'Genclik zirvesi'), ('tr', 'transist')], default='tr', max_length=15),
        ),
    ]
