# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bildirge', '0037_auto_20160728_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doc',
            name='event',
            field=models.CharField(choices=[(None, 'Lutfen seciniz'), ('gtz', 'Genclik zirvesi'), ('tr', 'transist')], default='None', max_length=15),
        ),
    ]
